# Chapter 8 - Introduction to Pytorch

## Installing Pytorch

In [14]:
%pip install torch


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [15]:
import torch
torch.__version__

'2.7.1'

## Comparing Tensors with NumPy Arrays

In [16]:
import torch
import numpy as np

# NumPy array
np_array = np.array([[1, 2], [3, 4]])

# PyTorch Tensor
tensor = torch.tensor([[1, 2], [3, 4]])

# Converting between NumPy arrays and PyTorch tensors
tensor_from_numpy = torch.from_numpy(np_array)
numpy_from_tensor = tensor.numpy()

print(tensor_from_numpy)
print(numpy_from_tensor)


tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


## Broadcasting

In [17]:
import torch

# Broadcasting example
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([10, 20])
result = tensor_a + tensor_b
print(result)


tensor([[11, 22],
        [13, 24]])


## Slicing and indexing

In [18]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing the first row
print(tensor[0, :])
# Modifying the first element
tensor[0, 0] = 99
print(tensor)


tensor([1, 2, 3])
tensor([[99,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])


## GPU Accleration with CUDA

In [19]:
import torch
import time

# Perform matrix multiplication on CPU
tensor_cpu = torch.randn(10000, 10000)
start_time = time.time()
tensor_cpu.matmul(tensor_cpu)
print(f"CPU Time: {time.time() - start_time} seconds")

# Perform matrix multiplication on GPU (if available)
if torch.cuda.is_available():
    tensor_gpu = tensor_cpu.cuda()
    start_time = time.time()
    tensor_gpu.matmul(tensor_gpu)
    print(f"GPU Time: {time.time() - start_time} seconds")


CPU Time: 0.689349889755249 seconds


## multi-GPU setups

In [20]:
import torch
import torch.nn as nn

# Define a simple neural network model
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.fc2 = nn.Linear(50, 2)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Instantiate the model
model = SimpleNet()

# Check if multiple GPUs are available and apply DataParallel
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if torch.cuda.device_count() > 1:
    model = nn.DataParallel(model)

# Move the model to the GPU(s)
model.to(device)

# Create dummy input for testing
input_data = torch.randn(64, 10).to(device)  # Batch of 64, input size 10

# Forward pass (distributed across GPUs if available)
output = model(input_data)
print(output)

tensor([[ 0.3457, -0.7519],
        [-0.4454, -0.2955],
        [-0.2049, -0.7980],
        [ 0.1510, -0.4797],
        [ 0.3881, -0.4644],
        [ 0.3080, -0.4172],
        [-0.3763, -0.3991],
        [ 0.0653, -0.2205],
        [ 0.1360, -0.4154],
        [ 0.2119, -0.2379],
        [ 0.1688, -0.8273],
        [-0.2270, -0.6435],
        [-0.1377,  0.0607],
        [-0.0548, -0.2788],
        [-0.0807, -0.5048],
        [ 0.2066, -0.4694],
        [-0.2673, -0.2676],
        [ 0.1637, -0.5430],
        [ 0.2232, -0.3232],
        [-0.3094, -0.5050],
        [-0.2864, -0.4547],
        [ 0.1616, -0.4223],
        [-0.1409, -0.2040],
        [-0.0871, -0.2732],
        [ 0.0534, -0.3452],
        [-0.0466, -0.2990],
        [ 0.1472, -0.4021],
        [ 0.0600, -0.5267],
        [ 0.1860, -0.3778],
        [-0.1111, -0.2682],
        [ 0.2692, -0.1694],
        [-0.2777, -0.3417],
        [ 0.2133, -0.3337],
        [-0.4025, -0.9125],
        [-0.1171,  0.0303],
        [-0.2822, -0

# Automatic Differentiation and Gradients
## Using Autograd to Compute Gradients

In [21]:
x = torch.tensor([2.0], requires_grad=True)
y = x ** 2
y.backward()  # Compute the gradient
print(x.grad)  # Gradient of y with respect to x is 2x


tensor([4.])


In [22]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x ** 3  # Some arbitrary operation
y.backward(torch.tensor([1.0, 0.5, 0.25]))  # Custom gradient
print(x.grad)

tensor([3.0000, 6.0000, 6.7500])


In [23]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x ** 3  # Some arbitrary operation
y.backward(torch.tensor([1.0, 0.5, 0.25]))  # Custom gradient
print(x.grad)


tensor([3.0000, 6.0000, 6.7500])


# Building Neural Networks in PyTorch

## Creating a Simple Neural Network

In [24]:
import torch.nn as nn

class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(4, 16)  # Input layer (4 features) to hidden layer (16 neurons)
        self.fc2 = nn.Linear(16, 3)  # Hidden layer to output layer (3 classes)

    def forward(self, x):
        x = torch.relu(self.fc1(x))  # Activation function
        x = self.fc2(x)
        return x


## Simple CNN

In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3)  # Input: 1 channel, output: 32 channels
        self.pool = nn.MaxPool2d(2, 2)  # Max pooling with a 2x2 window
        # We will initialize fc1 later dynamically

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))  # Apply conv, ReLU, and pooling
        x = x.view(x.size(0), -1)  # Flatten the tensor
        # Fully connected layer input size should match flattened size, calculate dynamically
        if not hasattr(self, 'fc1'):
            self.fc1 = nn.Linear(x.size(1), 10)  # Dynamically set based on input size
        x = self.fc1(x)  # Pass through fully connected layer
        return x

# Instantiate the model
model = SimpleCNN()

# Define a dummy input (batch size: 8, channels: 1, height: 28, width: 28)
input_data = torch.randn(8, 1, 28, 28)

# Forward pass
output = model(input_data)
print(output.shape)  # Output should be (8, 10), where 10 is the number of output classes

torch.Size([8, 10])
